[bot_server]
listen_address = "0.0.0.0:7978"

[ws_server]
listen_address = "0.0.0.0:7979"

[[botnode]]
markets = [
	"BTC/USDC",
	"ETH/USDC",
	"ETH/USDT",
	"SOL/USDC",
	"SOL/USDT",
	"FTT/USDC",
	"FTT/USDT",
	"BNB/USDC",
]
exchanges = ["ftx", "binance", "serum"]
