[workspace]
members = [
	"botnode",
	"botvana",
	"botvana-server",
	"research/async-runtime-bench",
	"research/engine-channels-bench",
	"research/tokio-thread-per-core",
	"server-test",
	"station-egui",
]
